/**
 * Random-link / lat-lon catalog for ~100 US cities.
 * SEO page copy lives in `city-metadata`; autocomplete in `city-database`.
 * Prefer importing via `@/lib/cities`.
 */
export const CITY_DATA = {
  'new-york-ny': {
    name: 'New York',
    state: 'NY',
    searchTerm: 'New York, NY',
    lat: 40.7128,
    lon: -74.0060,
    title: 'New York Weather Forecast - 16 Bit Weather',
    description: 'Current weather conditions and 5-day forecast for New York, NY. Real-time weather data with retro terminal aesthetics. Check temperature, humidity, wind, and more.',
    content: {
      intro: 'New York City experiences a humid subtropical climate with four distinct seasons. Located in the northeastern United States, the city\'s weather is influenced by its coastal position and urban heat island effect.',
      climate: 'Summers in NYC are typically hot and humid with average highs in the mid-80s°F (29°C), while winters are cold with temperatures often dropping below freezing. The city receives about 50 inches of precipitation annually, distributed fairly evenly throughout the year.',
      patterns: 'Weather patterns in New York are heavily influenced by the Atlantic Ocean and can change rapidly. The city experiences everything from nor\'easters in winter to thunderstorms and occasional heat waves in summer. Spring and fall offer the most pleasant weather conditions.'
    }
  },
  'los-angeles-ca': {
    name: 'Los Angeles',
    state: 'CA',
    searchTerm: 'Los Angeles, CA',
    lat: 34.0522,
    lon: -118.2437,
    title: 'Los Angeles Weather Forecast - 16 Bit Weather',
    description: 'Current weather conditions and 5-day forecast for Los Angeles, CA. Real-time weather data with retro terminal aesthetics. Check temperature, humidity, wind, and more.',
    content: {
      intro: 'Los Angeles enjoys a Mediterranean climate characterized by warm, dry summers and mild, wet winters. The city\'s location along the Pacific coast and surrounded by mountains creates diverse microclimates throughout the region.',
      climate: 'Summer temperatures typically range from the mid-70s to mid-80s°F (24-29°C) with very low humidity and minimal rainfall. Winters are mild with highs in the 60s-70s°F (15-21°C) and most of the year\'s 15 inches of rainfall occurring between November and March.',
      patterns: 'LA\'s weather is notably stable and predictable, with over 280 sunny days per year. The marine layer from the Pacific often creates morning fog and clouds that burn off by afternoon. Santa Ana winds occasionally bring hot, dry conditions and elevated fire risk.'
    }
  },
  'chicago-il': {
    name: 'Chicago',
    state: 'IL',
    searchTerm: 'Chicago, IL',
    lat: 41.8781,
    lon: -87.6298,
    title: 'Chicago Weather Forecast - 16 Bit Weather',
    description: 'Current weather conditions and 5-day forecast for Chicago, IL. Real-time weather data with retro terminal aesthetics. Check temperature, humidity, wind, and more.',
    content: {
      intro: 'Chicago experiences a continental climate with hot, humid summers and cold, snowy winters. The city\'s location on Lake Michigan significantly influences its weather patterns, moderating temperatures and increasing precipitation.',
      climate: 'Summer highs average in the low 80s°F (27°C) with high humidity, while winter temperatures often drop below freezing with average lows around 20°F (-7°C). The city receives about 38 inches of precipitation annually, including significant snowfall in winter.',
      patterns: 'Lake Michigan creates a "lake effect" that moderates temperatures year-round but can enhance snowfall in winter. The city is known for its rapidly changing weather and strong winds, earning it the nickname "Windy City." Spring and fall are transitional with variable conditions.'
    }
  },
  'houston-tx': {
    name: 'Houston',
    state: 'TX',
    searchTerm: 'Houston, TX',
    lat: 29.7604,
    lon: -95.3698,
    title: 'Houston Weather Forecast - 16 Bit Weather',
    description: 'Current weather conditions and 5-day forecast for Houston, TX. Real-time weather data with retro terminal aesthetics. Check temperature, humidity, wind, and more.',
    content: {
      intro: 'Houston has a humid subtropical climate with hot, humid summers and mild winters. Located near the Gulf of Mexico, the city experiences high humidity year-round and is prone to tropical weather systems.',
      climate: 'Summer temperatures regularly reach the 90s°F (32-37°C) with very high humidity making it feel even hotter. Winters are mild with highs in the 60s-70s°F (15-21°C). The city receives about 50 inches of rain annually, much of it from thunderstorms and tropical systems.',
      patterns: 'Houston\'s weather is dominated by Gulf moisture creating frequent afternoon and evening thunderstorms during summer. The city is vulnerable to hurricanes and tropical storms from June through November. Heat and humidity can make summer conditions particularly challenging.'
    }
  },
  'phoenix-az': {
    name: 'Phoenix',
    state: 'AZ',
    searchTerm: 'Phoenix, AZ',
    lat: 33.4484,
    lon: -112.0740,
    title: 'Phoenix Weather Forecast - 16 Bit Weather',
    description: 'Current weather conditions and 5-day forecast for Phoenix, AZ. Real-time weather data with retro terminal aesthetics. Check temperature, humidity, wind, and more.',
    content: {
      intro: 'Phoenix has a hot desert climate with extremely hot summers and mild winters. Located in the Sonoran Desert, the city experiences low humidity year-round and abundant sunshine with minimal precipitation.',
      climate: 'Summer temperatures routinely exceed 110°F (43°C) from May through September, making Phoenix one of the hottest major cities in the US. Winters are pleasant with highs in the 70s°F (21°C). Annual rainfall is only about 8 inches, mostly from winter storms and summer monsoons.',
      patterns: 'Phoenix weather is characterized by extreme heat and drought, broken by the North American Monsoon which brings thunderstorms and flash flooding from July through September. Winter months offer ideal outdoor weather conditions with clear skies and comfortable temperatures.'
    }
  },
  // Additional cities with basic data
  'philadelphia-pa': { name: 'Philadelphia', state: 'PA', searchTerm: 'Philadelphia, PA', lat: 39.9526, lon: -75.1652 },
  'san-antonio-tx': { name: 'San Antonio', state: 'TX', searchTerm: 'San Antonio, TX', lat: 29.4241, lon: -98.4936 },
  'san-diego-ca': { name: 'San Diego', state: 'CA', searchTerm: 'San Diego, CA', lat: 32.7157, lon: -117.1611 },
  'dallas-tx': { name: 'Dallas', state: 'TX', searchTerm: 'Dallas, TX', lat: 32.7767, lon: -96.7970 },
  'austin-tx': { name: 'Austin', state: 'TX', searchTerm: 'Austin, TX', lat: 30.2672, lon: -97.7431 },
  'salt-lake-city-ut': { name: 'Salt Lake City', state: 'UT', searchTerm: 'Salt Lake City, UT', lat: 40.7608, lon: -111.8910 },
  'san-jose-ca': { name: 'San Jose', state: 'CA', searchTerm: 'San Jose, CA', lat: 37.3382, lon: -121.8863 },
  'jacksonville-fl': { name: 'Jacksonville', state: 'FL', searchTerm: 'Jacksonville, FL', lat: 30.3322, lon: -81.6557 },
  'fort-worth-tx': { name: 'Fort Worth', state: 'TX', searchTerm: 'Fort Worth, TX', lat: 32.7555, lon: -97.3308 },
  'columbus-oh': { name: 'Columbus', state: 'OH', searchTerm: 'Columbus, OH', lat: 39.9612, lon: -82.9988 },
  'charlotte-nc': { name: 'Charlotte', state: 'NC', searchTerm: 'Charlotte, NC', lat: 35.2271, lon: -80.8431 },
  'indianapolis-in': { name: 'Indianapolis', state: 'IN', searchTerm: 'Indianapolis, IN', lat: 39.7684, lon: -86.1581 },
  'san-francisco-ca': { name: 'San Francisco', state: 'CA', searchTerm: 'San Francisco, CA', lat: 37.7749, lon: -122.4194 },
  'seattle-wa': { name: 'Seattle', state: 'WA', searchTerm: 'Seattle, WA', lat: 47.6062, lon: -122.3321 },
  'denver-co': { name: 'Denver', state: 'CO', searchTerm: 'Denver, CO', lat: 39.7392, lon: -104.9903 },
  'washington-dc': { name: 'Washington', state: 'DC', searchTerm: 'Washington, DC', lat: 38.9072, lon: -77.0369 },
  'boston-ma': { name: 'Boston', state: 'MA', searchTerm: 'Boston, MA', lat: 42.3601, lon: -71.0589 },
  'el-paso-tx': { name: 'El Paso', state: 'TX', searchTerm: 'El Paso, TX', lat: 31.7619, lon: -106.4850 },
  'nashville-tn': { name: 'Nashville', state: 'TN', searchTerm: 'Nashville, TN', lat: 36.1627, lon: -86.7816 },
  'detroit-mi': { name: 'Detroit', state: 'MI', searchTerm: 'Detroit, MI', lat: 42.3314, lon: -83.0458 },
  'oklahoma-city-ok': { name: 'Oklahoma City', state: 'OK', searchTerm: 'Oklahoma City, OK', lat: 35.4676, lon: -97.5164 },
  'portland-or': { name: 'Portland', state: 'OR', searchTerm: 'Portland, OR', lat: 45.5152, lon: -122.6784 },
  'las-vegas-nv': { name: 'Las Vegas', state: 'NV', searchTerm: 'Las Vegas, NV', lat: 36.1699, lon: -115.1398 },
  'memphis-tn': { name: 'Memphis', state: 'TN', searchTerm: 'Memphis, TN', lat: 35.1495, lon: -90.0490 },
  'louisville-ky': { name: 'Louisville', state: 'KY', searchTerm: 'Louisville, KY', lat: 38.2527, lon: -85.7585 },
  'baltimore-md': { name: 'Baltimore', state: 'MD', searchTerm: 'Baltimore, MD', lat: 39.2904, lon: -76.6122 },
  'milwaukee-wi': { name: 'Milwaukee', state: 'WI', searchTerm: 'Milwaukee, WI', lat: 43.0389, lon: -87.9065 },
  'albuquerque-nm': { name: 'Albuquerque', state: 'NM', searchTerm: 'Albuquerque, NM', lat: 35.0853, lon: -106.6056 },
  'tucson-az': { name: 'Tucson', state: 'AZ', searchTerm: 'Tucson, AZ', lat: 32.2226, lon: -110.9747 },
  'fresno-ca': { name: 'Fresno', state: 'CA', searchTerm: 'Fresno, CA', lat: 36.7378, lon: -119.7871 },
  'sacramento-ca': { name: 'Sacramento', state: 'CA', searchTerm: 'Sacramento, CA', lat: 38.5816, lon: -121.4944 },
  'kansas-city-mo': { name: 'Kansas City', state: 'MO', searchTerm: 'Kansas City, MO', lat: 39.0997, lon: -94.5786 },
  'long-beach-ca': { name: 'Long Beach', state: 'CA', searchTerm: 'Long Beach, CA', lat: 33.7701, lon: -118.1937 },
  'mesa-az': { name: 'Mesa', state: 'AZ', searchTerm: 'Mesa, AZ', lat: 33.4152, lon: -111.8315 },
  'atlanta-ga': { name: 'Atlanta', state: 'GA', searchTerm: 'Atlanta, GA', lat: 33.7490, lon: -84.3880 },
  'colorado-springs-co': { name: 'Colorado Springs', state: 'CO', searchTerm: 'Colorado Springs, CO', lat: 38.8339, lon: -104.8214 },
  'virginia-beach-va': { name: 'Virginia Beach', state: 'VA', searchTerm: 'Virginia Beach, VA', lat: 36.8529, lon: -75.9780 },
  'raleigh-nc': { name: 'Raleigh', state: 'NC', searchTerm: 'Raleigh, NC', lat: 35.7796, lon: -78.6382 },
  'omaha-ne': { name: 'Omaha', state: 'NE', searchTerm: 'Omaha, NE', lat: 41.2565, lon: -95.9345 },
  'miami-fl': { name: 'Miami', state: 'FL', searchTerm: 'Miami, FL', lat: 25.7617, lon: -80.1918 },
  'oakland-ca': { name: 'Oakland', state: 'CA', searchTerm: 'Oakland, CA', lat: 37.8044, lon: -122.2712 },
  'minneapolis-mn': { name: 'Minneapolis', state: 'MN', searchTerm: 'Minneapolis, MN', lat: 44.9778, lon: -93.2650 },
  'tulsa-ok': { name: 'Tulsa', state: 'OK', searchTerm: 'Tulsa, OK', lat: 36.1540, lon: -95.9928 },
  'wichita-ks': { name: 'Wichita', state: 'KS', searchTerm: 'Wichita, KS', lat: 37.6872, lon: -97.3301 },
  'new-orleans-la': { name: 'New Orleans', state: 'LA', searchTerm: 'New Orleans, LA', lat: 29.9511, lon: -90.0715 },
  'cleveland-oh': { name: 'Cleveland', state: 'OH', searchTerm: 'Cleveland, OH', lat: 41.4993, lon: -81.6944 },
  'tampa-fl': { name: 'Tampa', state: 'FL', searchTerm: 'Tampa, FL', lat: 27.9506, lon: -82.4572 },
  'aurora-co': { name: 'Aurora', state: 'CO', searchTerm: 'Aurora, CO', lat: 39.7294, lon: -104.8319 },
  'honolulu-hi': { name: 'Honolulu', state: 'HI', searchTerm: 'Honolulu, HI', lat: 21.3099, lon: -157.8581 },
  'anaheim-ca': { name: 'Anaheim', state: 'CA', searchTerm: 'Anaheim, CA', lat: 33.8366, lon: -117.9143 },
  'santa-ana-ca': { name: 'Santa Ana', state: 'CA', searchTerm: 'Santa Ana, CA', lat: 33.7455, lon: -117.8677 },
  'st-louis-mo': { name: 'St Louis', state: 'MO', searchTerm: 'St Louis, MO', lat: 38.6270, lon: -90.1994 },
  'riverside-ca': { name: 'Riverside', state: 'CA', searchTerm: 'Riverside, CA', lat: 33.9806, lon: -117.3755 },
  'corpus-christi-tx': { name: 'Corpus Christi', state: 'TX', searchTerm: 'Corpus Christi, TX', lat: 27.8006, lon: -97.3964 },
  'pittsburgh-pa': { name: 'Pittsburgh', state: 'PA', searchTerm: 'Pittsburgh, PA', lat: 40.4406, lon: -79.9959 },
  'lexington-ky': { name: 'Lexington', state: 'KY', searchTerm: 'Lexington, KY', lat: 38.0406, lon: -84.5037 },
  'anchorage-ak': { name: 'Anchorage', state: 'AK', searchTerm: 'Anchorage, AK', lat: 61.2181, lon: -149.9003 },
  'stockton-ca': { name: 'Stockton', state: 'CA', searchTerm: 'Stockton, CA', lat: 37.9577, lon: -121.2908 },
  'cincinnati-oh': { name: 'Cincinnati', state: 'OH', searchTerm: 'Cincinnati, OH', lat: 39.1031, lon: -84.5120 },
  'st-paul-mn': { name: 'St Paul', state: 'MN', searchTerm: 'St Paul, MN', lat: 44.9537, lon: -93.0900 },
  'toledo-oh': { name: 'Toledo', state: 'OH', searchTerm: 'Toledo, OH', lat: 41.6528, lon: -83.5379 },
  'greensboro-nc': { name: 'Greensboro', state: 'NC', searchTerm: 'Greensboro, NC', lat: 36.0726, lon: -79.7920 },
  'newark-nj': { name: 'Newark', state: 'NJ', searchTerm: 'Newark, NJ', lat: 40.7357, lon: -74.1724 },
  'plano-tx': { name: 'Plano', state: 'TX', searchTerm: 'Plano, TX', lat: 33.0198, lon: -96.6989 },
  'henderson-nv': { name: 'Henderson', state: 'NV', searchTerm: 'Henderson, NV', lat: 36.0395, lon: -114.9817 },
  'lincoln-ne': { name: 'Lincoln', state: 'NE', searchTerm: 'Lincoln, NE', lat: 40.8136, lon: -96.7026 },
  'buffalo-ny': { name: 'Buffalo', state: 'NY', searchTerm: 'Buffalo, NY', lat: 42.8864, lon: -78.8784 },
  'jersey-city-nj': { name: 'Jersey City', state: 'NJ', searchTerm: 'Jersey City, NJ', lat: 40.7282, lon: -74.0776 },
  'chula-vista-ca': { name: 'Chula Vista', state: 'CA', searchTerm: 'Chula Vista, CA', lat: 32.6401, lon: -117.0842 },
  'fort-wayne-in': { name: 'Fort Wayne', state: 'IN', searchTerm: 'Fort Wayne, IN', lat: 41.0793, lon: -85.1394 },
  'orlando-fl': { name: 'Orlando', state: 'FL', searchTerm: 'Orlando, FL', lat: 28.5383, lon: -81.3792 },
  'st-petersburg-fl': { name: 'St Petersburg', state: 'FL', searchTerm: 'St Petersburg, FL', lat: 27.7676, lon: -82.6403 },
  'chandler-az': { name: 'Chandler', state: 'AZ', searchTerm: 'Chandler, AZ', lat: 33.3062, lon: -111.8413 },
  'laredo-tx': { name: 'Laredo', state: 'TX', searchTerm: 'Laredo, TX', lat: 27.5306, lon: -99.4803 },
  'norfolk-va': { name: 'Norfolk', state: 'VA', searchTerm: 'Norfolk, VA', lat: 36.8508, lon: -76.2859 },
  'durham-nc': { name: 'Durham', state: 'NC', searchTerm: 'Durham, NC', lat: 35.9940, lon: -78.8986 },
  'madison-wi': { name: 'Madison', state: 'WI', searchTerm: 'Madison, WI', lat: 43.0731, lon: -89.4012 },
  'lubbock-tx': { name: 'Lubbock', state: 'TX', searchTerm: 'Lubbock, TX', lat: 33.5779, lon: -101.8552 },
  'irvine-ca': { name: 'Irvine', state: 'CA', searchTerm: 'Irvine, CA', lat: 33.6846, lon: -117.8265 },
  'winston-salem-nc': { name: 'Winston-Salem', state: 'NC', searchTerm: 'Winston-Salem, NC', lat: 36.0999, lon: -80.2442 },
  'glendale-az': { name: 'Glendale', state: 'AZ', searchTerm: 'Glendale, AZ', lat: 33.5387, lon: -112.1860 },
  'garland-tx': { name: 'Garland', state: 'TX', searchTerm: 'Garland, TX', lat: 32.9126, lon: -96.6389 },
  'hialeah-fl': { name: 'Hialeah', state: 'FL', searchTerm: 'Hialeah, FL', lat: 25.8576, lon: -80.2781 },
  'reno-nv': { name: 'Reno', state: 'NV', searchTerm: 'Reno, NV', lat: 39.5296, lon: -119.8138 },
  'chesapeake-va': { name: 'Chesapeake', state: 'VA', searchTerm: 'Chesapeake, VA', lat: 36.7682, lon: -76.2875 },
  'gilbert-az': { name: 'Gilbert', state: 'AZ', searchTerm: 'Gilbert, AZ', lat: 33.3528, lon: -111.7890 },
  'baton-rouge-la': { name: 'Baton Rouge', state: 'LA', searchTerm: 'Baton Rouge, LA', lat: 30.4515, lon: -91.1871 },
  'irving-tx': { name: 'Irving', state: 'TX', searchTerm: 'Irving, TX', lat: 32.8140, lon: -96.9489 },
  'scottsdale-az': { name: 'Scottsdale', state: 'AZ', searchTerm: 'Scottsdale, AZ', lat: 33.4942, lon: -111.9261 },
  'north-las-vegas-nv': { name: 'North Las Vegas', state: 'NV', searchTerm: 'North Las Vegas, NV', lat: 36.1989, lon: -115.1175 },
  'fremont-ca': { name: 'Fremont', state: 'CA', searchTerm: 'Fremont, CA', lat: 37.5485, lon: -121.9886 },
  'boise-id': { name: 'Boise', state: 'ID', searchTerm: 'Boise, ID', lat: 43.6150, lon: -116.2023 },
  'richmond-va': { name: 'Richmond', state: 'VA', searchTerm: 'Richmond, VA', lat: 37.5407, lon: -77.4360 },
  'san-bernardino-ca': { name: 'San Bernardino', state: 'CA', searchTerm: 'San Bernardino, CA', lat: 34.1083, lon: -117.2898 },
  'spokane-wa': { name: 'Spokane', state: 'WA', searchTerm: 'Spokane, WA', lat: 47.6588, lon: -117.4260 }
}

// Export for use in other files
